package models

import "time"

type FormatType int

const (
	FormatMD   FormatType = 0
	FormatHTML FormatType = 1
	FormatDOCX FormatType = 2
)

type PostStatus int

const (
	StatusReleased PostStatus = 0
	StatusPending  PostStatus = 1
	StatusReject   PostStatus = -1
)

// PostConfig load configuration of single post from config.toml
type PostConfig struct {
	// MemberID is the id from database which should resolved by doc-provider and the original data comes from database
	MemberID int `toml:"member_id"`

	// Author can be nick or real name (It depends on the goadKeeper)
	Author string `toml:"author"`

	// Email is optional
	Email string `toml:"email"`

	// IndexFormat is the format fo index.unknown
	IndexFormat FormatType `toml:"index_format"`

	// Title is single line string for the post
	Title string `toml:"title"`

	// Overview provides overall inforamtion about this post which should be displayed on frontend
	Overview string `toml:"overview"`

	// NOTE:
	// PostID
	// When Post is new, it will be -1
	// When post is rejected or updated, it will be the original id the database assigned
	PostID int `toml:"post_id"`

	// Tags
	// WARN: Create if not exist and total tag is less than 20 else discards specific tag
	Tags []string `toml:"tags"`
}

// PostRow which defined for database insert and update
type PostRow struct {
	// Title comes from PostConfig
	Title string `json:"title"`

	// Author comes from PostConfig
	Author string `json:"author"`

	// Overview for post
	Overview string `json:"overview"`

	// Content raw content of this post
	Content string `json:"content"`

	// Format of the index.unknown
	Format FormatType `json:"format"`

	// Status
	// -1 is reject
	// 0 is released
	// 1 is pending
	Status PostStatus `json:"status"`

	// ViewCount
	// init with value 0
	ViewCount int `json:"view_count"`

	// CreateTime of this post, generated by sqlite3
	CreateTime time.Time `json:"create_time"`

	// UpdateTime of this post
	UpdateTime time.Time `json:"update_time"`
}
