# 成员 id (由后端添加成员的时候生成)
member_id = 1

# 作者名称 (允许昵称)
author = "张三"

# 邮箱 可选, 没有填写放空即可
email = ""

# 主文件类型
# TODO: 可选项 [ md, html, docx ]
# WARN: 当前支持 [ md, html ]
# 0 md
# 1 html
# 2 docx
index_format = 0

# 文章标题
title = "如何做好一个golang后端"

# 文章概要(多行使用三个双引号)
overview = """
这是一篇关于如何做好golang后端的文章.
主要涉及接口设计， 系统分析，流程图制作等
"""


# NOTE: 如果是全新的文章则不需要填写
# WARN: 如果是退回的或者更新的文章需要填写
# TODO: 通过简易的 html 页面查看文章列表
post_id = -1

# 直接写标签, 如果不存在则自动创建新的标签
# 每个文章只支持 3 个标签以内
# WARN: 如果系统的总标签数量超过 20 则会拒绝创建
# 查看网页前端获取现在已有的标签
tags = ["golang", "CS"]
